#ifndef CUSTOM_GRAPHICS_HPP
#define CUSTOM_GRAPHICS_HPP

#include "../Source/Basic/basic_includes.hpp"
#include "../Source/Graphics/color.hpp"
#include "../Source/Graphics/hsl_color.hpp"
#include "../Source/Graphics/packed_color.hpp"

#include "../Source/Graphics/camera_2d.hpp"
#include "../Source/Graphics/camera_3d.hpp"
#include "../Source/Graphics/mesh.hpp"
#include "../Source/Graphics/ray.hpp"
#include "../Source/Graphics/lighting_3d.hpp"

#include "../Source/Vulkan/include.hpp"
#include "../Source/OpenGL/include.hpp"
#include "../Source/GPU/include.hpp"

#include "../Source/Input/keys.hpp"
#include "../Source/Input/input_types.hpp"
#include "../Source/Input/gestures.hpp"
#include "../Source/Input/gamepad_mapping.hpp"
#include "../Source/Input/gamepad.hpp"

#include "../Source/Windows/window_types.hpp"
#include "../Source/Windows/window.hpp"
#include "../Source/Windows/dialogs.hpp"
#include "../Source/Windows/renderer.hpp"
#include "../Source/Windows/game_loop.hpp"
#include "../Source/Windows/input_manager.hpp"
#include "../Source/Windows/raster_3d.hpp"

#include "../Source/System/include.hpp"
#include "../Source/System/process.hpp"
#include "../Source/GPU/shader_bundle.hpp"
#include "../Source/GPU/material.hpp"
#include "../Source/GPU/render_queue.hpp"
#include "../Source/GPU/shader_reload.hpp"

#include "../Source/Util Hpp/json.hpp"
#include "../Source/Util Hpp/ease_tween.hpp"
#include "../Source/Util Hpp/tween_extras.hpp"
#include "../Source/Images/Normal/png_codec.hpp"
#include "../Source/Images/Normal/jpeg_codec.hpp"
#include "../Source/Graphics/draw_types_2d.hpp"
#include "../Source/Graphics/nine_slice.hpp"
#include "../Source/Graphics/tilemap.hpp"
#include "../Source/Graphics/particles_2d.hpp"
#include "../Source/Graphics/trail_2d.hpp"
#include "../Source/Graphics/scene_graph_2d.hpp"
#include "../Source/Graphics/texture_atlas.hpp"
#include "../Source/Graphics/asset_manager.hpp"
#include "../Source/Graphics/camera_controller_2d.hpp"
#include "../Source/Graphics/collision_2d.hpp"
#include "../Source/Graphics/model_3d.hpp"
#include "../Source/UI/ui.hpp"
#include "../Source/Text/fancy_text.hpp"
#include "../Source/Text/fancy_text_render.hpp"
#include "../Source/Text/fancy_math.hpp"
#include "../Source/Text/math_files.hpp"

#endif //CUSTOM_GRAPHICS_HPP