#ifndef FIZMO_MATHTEXT_SYMBOLS_RELATIONS_HPP
#define FIZMO_MATHTEXT_SYMBOLS_RELATIONS_HPP

#include "symbol_types.hpp"

namespace fizmo {
namespace mathtext {

inline constexpr SymbolInfo kRelationSymbols[] = {
    { { "lt", "less_than" }, "\x3C", 0x003C, SymbolClass::Relation },
    { { "gt", "greater_than" }, "\x3E", 0x003E, SymbolClass::Relation },
    { { "leq", "le", "less_equal", "less_or_equal", "less_than_or_equal" }, "\xE2\x89\xA4", 0x2264, SymbolClass::Relation },
    { { "geq", "ge", "greater_equal", "greater_or_equal", "greater_than_or_equal" }, "\xE2\x89\xA5", 0x2265, SymbolClass::Relation },
    { { "leqq" }, "\xE2\x89\xA6", 0x2266, SymbolClass::Relation },
    { { "geqq" }, "\xE2\x89\xA7", 0x2267, SymbolClass::Relation },
    { { "leqslant" }, "\xE2\xA9\xBD", 0x2A7D, SymbolClass::Relation },
    { { "geqslant" }, "\xE2\xA9\xBE", 0x2A7E, SymbolClass::Relation },
    { { "eqslantless" }, "\xE2\xAA\x95", 0x2A95, SymbolClass::Relation },
    { { "eqslantgtr" }, "\xE2\xAA\x96", 0x2A96, SymbolClass::Relation },
    { { "ll", "much_less" }, "\xE2\x89\xAA", 0x226A, SymbolClass::Relation },
    { { "gg", "much_greater" }, "\xE2\x89\xAB", 0x226B, SymbolClass::Relation },
    { { "lll" }, "\xE2\x8B\x98", 0x22D8, SymbolClass::Relation },
    { { "ggg" }, "\xE2\x8B\x99", 0x22D9, SymbolClass::Relation },
    { { "lessdot" }, "\xE2\x8B\x96", 0x22D6, SymbolClass::Relation },
    { { "gtrdot" }, "\xE2\x8B\x97", 0x22D7, SymbolClass::Relation },
    { { "lesssim" }, "\xE2\x89\xB2", 0x2272, SymbolClass::Relation },
    { { "gtrsim" }, "\xE2\x89\xB3", 0x2273, SymbolClass::Relation },
    { { "lessapprox" }, "\xE2\xAA\x85", 0x2A85, SymbolClass::Relation },
    { { "gtrapprox" }, "\xE2\xAA\x86", 0x2A86, SymbolClass::Relation },
    { { "lessgtr" }, "\xE2\x89\xB6", 0x2276, SymbolClass::Relation },
    { { "gtrless" }, "\xE2\x89\xB7", 0x2277, SymbolClass::Relation },
    { { "lesseqgtr" }, "\xE2\x8B\x9A", 0x22DA, SymbolClass::Relation },
    { { "gtreqless" }, "\xE2\x8B\x9B", 0x22DB, SymbolClass::Relation },
    { { "equiv", "identical", "equivalent" }, "\xE2\x89\xA1", 0x2261, SymbolClass::Relation },
    { { "approx", "thickapprox", "approximately", "approximately_equal" }, "\xE2\x89\x88", 0x2248, SymbolClass::Relation },
    { { "approxeq", "approximately_equal_to" }, "\xE2\x89\x8A", 0x224A, SymbolClass::Relation },
    { { "sim", "thicksim", "similar" }, "\xE2\x88\xBC", 0x223C, SymbolClass::Relation },
    { { "backsim" }, "\xE2\x88\xBD", 0x223D, SymbolClass::Relation },
    { { "simeq", "similar_equal" }, "\xE2\x89\x83", 0x2243, SymbolClass::Relation },
    { { "backsimeq" }, "\xE2\x8B\x8D", 0x22CD, SymbolClass::Relation },
    { { "cong", "congruent" }, "\xE2\x89\x85", 0x2245, SymbolClass::Relation },
    { { "asymp" }, "\xE2\x89\x8D", 0x224D, SymbolClass::Relation },
    { { "bumpeq" }, "\xE2\x89\x8F", 0x224F, SymbolClass::Relation },
    { { "Bumpeq" }, "\xE2\x89\x8E", 0x224E, SymbolClass::Relation },
    { { "doteq" }, "\xE2\x89\x90", 0x2250, SymbolClass::Relation },
    { { "doteqdot", "Doteq" }, "\xE2\x89\x91", 0x2251, SymbolClass::Relation },
    { { "risingdotseq" }, "\xE2\x89\x93", 0x2253, SymbolClass::Relation },
    { { "fallingdotseq" }, "\xE2\x89\x92", 0x2252, SymbolClass::Relation },
    { { "eqcirc" }, "\xE2\x89\x96", 0x2256, SymbolClass::Relation },
    { { "circeq" }, "\xE2\x89\x97", 0x2257, SymbolClass::Relation },
    { { "triangleq" }, "\xE2\x89\x9C", 0x225C, SymbolClass::Relation },
    { { "coloneqq" }, "\xE2\x89\x94", 0x2254, SymbolClass::Relation },
    { { "eqqcolon" }, "\xE2\x89\x95", 0x2255, SymbolClass::Relation },
    { { "propto", "varpropto", "proportional_to" }, "\xE2\x88\x9D", 0x221D, SymbolClass::Relation },
    { { "prec" }, "\xE2\x89\xBA", 0x227A, SymbolClass::Relation },
    { { "succ" }, "\xE2\x89\xBB", 0x227B, SymbolClass::Relation },
    { { "preceq" }, "\xE2\xAA\xAF", 0x2AAF, SymbolClass::Relation },
    { { "succeq" }, "\xE2\xAA\xB0", 0x2AB0, SymbolClass::Relation },
    { { "preccurlyeq" }, "\xE2\x89\xBC", 0x227C, SymbolClass::Relation },
    { { "succcurlyeq" }, "\xE2\x89\xBD", 0x227D, SymbolClass::Relation },
    { { "precsim" }, "\xE2\x89\xBE", 0x227E, SymbolClass::Relation },
    { { "succsim" }, "\xE2\x89\xBF", 0x227F, SymbolClass::Relation },
    { { "subset", "subset_of" }, "\xE2\x8A\x82", 0x2282, SymbolClass::Relation },
    { { "supset", "superset_of" }, "\xE2\x8A\x83", 0x2283, SymbolClass::Relation },
    { { "subseteq", "subset_equal", "subset_or_equal" }, "\xE2\x8A\x86", 0x2286, SymbolClass::Relation },
    { { "supseteq", "superset_equal", "superset_or_equal" }, "\xE2\x8A\x87", 0x2287, SymbolClass::Relation },
    { { "Subset" }, "\xE2\x8B\x90", 0x22D0, SymbolClass::Relation },
    { { "Supset" }, "\xE2\x8B\x91", 0x22D1, SymbolClass::Relation },
    { { "sqsubset" }, "\xE2\x8A\x8F", 0x228F, SymbolClass::Relation },
    { { "sqsupset" }, "\xE2\x8A\x90", 0x2290, SymbolClass::Relation },
    { { "sqsubseteq" }, "\xE2\x8A\x91", 0x2291, SymbolClass::Relation },
    { { "sqsupseteq" }, "\xE2\x8A\x92", 0x2292, SymbolClass::Relation },
    { { "in", "element_of" }, "\xE2\x88\x88", 0x2208, SymbolClass::Relation },
    { { "ni", "owns", "contains" }, "\xE2\x88\x8B", 0x220B, SymbolClass::Relation },
    { { "backepsilon" }, "\xCF\xB6", 0x03F6, SymbolClass::Relation },
    { { "mid", "shortmid", "divides" }, "\xE2\x88\xA3", 0x2223, SymbolClass::Relation },
    { { "parallel", "shortparallel" }, "\xE2\x88\xA5", 0x2225, SymbolClass::Relation },
    { { "perp", "perpendicular" }, "\xE2\x8A\xA5", 0x22A5, SymbolClass::Relation },
    { { "models", "entails" }, "\xE2\x8A\xA7", 0x22A7, SymbolClass::Relation },
    { { "vdash", "proves" }, "\xE2\x8A\xA2", 0x22A2, SymbolClass::Relation },
    { { "dashv" }, "\xE2\x8A\xA3", 0x22A3, SymbolClass::Relation },
    { { "Vdash" }, "\xE2\x8A\xA9", 0x22A9, SymbolClass::Relation },
    { { "vDash" }, "\xE2\x8A\xA8", 0x22A8, SymbolClass::Relation },
    { { "Vvdash" }, "\xE2\x8A\xAA", 0x22AA, SymbolClass::Relation },
    { { "bowtie" }, "\xE2\x8B\x88", 0x22C8, SymbolClass::Relation },
    { { "Join" }, "\xE2\xA8\x9D", 0x2A1D, SymbolClass::Relation },
    { { "smile", "smallsmile" }, "\xE2\x8C\xA3", 0x2323, SymbolClass::Relation },
    { { "frown", "smallfrown" }, "\xE2\x8C\xA2", 0x2322, SymbolClass::Relation },
    { { "between" }, "\xE2\x89\xAC", 0x226C, SymbolClass::Relation },
    { { "pitchfork" }, "\xE2\x8B\x94", 0x22D4, SymbolClass::Relation },
    { { "vartriangleleft" }, "\xE2\x8A\xB2", 0x22B2, SymbolClass::Relation },
    { { "vartriangleright" }, "\xE2\x8A\xB3", 0x22B3, SymbolClass::Relation },
    { { "trianglelefteq" }, "\xE2\x8A\xB4", 0x22B4, SymbolClass::Relation },
    { { "trianglerighteq" }, "\xE2\x8A\xB5", 0x22B5, SymbolClass::Relation },
};

inline constexpr SymbolInfo kNegatedRelationSymbols[] = {
    { { "neq", "ne", "not_equal" }, "\xE2\x89\xA0", 0x2260, SymbolClass::NegatedRelation },
    { { "nless" }, "\xE2\x89\xAE", 0x226E, SymbolClass::NegatedRelation },
    { { "ngtr" }, "\xE2\x89\xAF", 0x226F, SymbolClass::NegatedRelation },
    { { "nleq" }, "\xE2\x89\xB0", 0x2270, SymbolClass::NegatedRelation },
    { { "ngeq" }, "\xE2\x89\xB1", 0x2271, SymbolClass::NegatedRelation },
    { { "lneq" }, "\xE2\xAA\x87", 0x2A87, SymbolClass::NegatedRelation },
    { { "gneq" }, "\xE2\xAA\x88", 0x2A88, SymbolClass::NegatedRelation },
    { { "lneqq" }, "\xE2\x89\xA8", 0x2268, SymbolClass::NegatedRelation },
    { { "gneqq" }, "\xE2\x89\xA9", 0x2269, SymbolClass::NegatedRelation },
    { { "lnsim" }, "\xE2\x8B\xA6", 0x22E6, SymbolClass::NegatedRelation },
    { { "gnsim" }, "\xE2\x8B\xA7", 0x22E7, SymbolClass::NegatedRelation },
    { { "lnapprox" }, "\xE2\xAA\x89", 0x2A89, SymbolClass::NegatedRelation },
    { { "gnapprox" }, "\xE2\xAA\x8A", 0x2A8A, SymbolClass::NegatedRelation },
    { { "nequiv" }, "\xE2\x89\xA2", 0x2262, SymbolClass::NegatedRelation },
    { { "napprox" }, "\xE2\x89\x89", 0x2249, SymbolClass::NegatedRelation },
    { { "nsim" }, "\xE2\x89\x81", 0x2241, SymbolClass::NegatedRelation },
    { { "ncong" }, "\xE2\x89\x87", 0x2247, SymbolClass::NegatedRelation },
    { { "nprec" }, "\xE2\x8A\x80", 0x2280, SymbolClass::NegatedRelation },
    { { "nsucc" }, "\xE2\x8A\x81", 0x2281, SymbolClass::NegatedRelation },
    { { "npreceq" }, "\xE2\x8B\xA0", 0x22E0, SymbolClass::NegatedRelation },
    { { "nsucceq" }, "\xE2\x8B\xA1", 0x22E1, SymbolClass::NegatedRelation },
    { { "precneqq" }, "\xE2\xAA\xB5", 0x2AB5, SymbolClass::NegatedRelation },
    { { "succneqq" }, "\xE2\xAA\xB6", 0x2AB6, SymbolClass::NegatedRelation },
    { { "precnsim" }, "\xE2\x8B\xA8", 0x22E8, SymbolClass::NegatedRelation },
    { { "succnsim" }, "\xE2\x8B\xA9", 0x22E9, SymbolClass::NegatedRelation },
    { { "notin", "not_element_of" }, "\xE2\x88\x89", 0x2209, SymbolClass::NegatedRelation },
    { { "nni" }, "\xE2\x88\x8C", 0x220C, SymbolClass::NegatedRelation },
    { { "nsubset" }, "\xE2\x8A\x84", 0x2284, SymbolClass::NegatedRelation },
    { { "nsupset" }, "\xE2\x8A\x85", 0x2285, SymbolClass::NegatedRelation },
    { { "nsubseteq", "not_subset_equal" }, "\xE2\x8A\x88", 0x2288, SymbolClass::NegatedRelation },
    { { "nsupseteq" }, "\xE2\x8A\x89", 0x2289, SymbolClass::NegatedRelation },
    { { "subsetneq", "proper_subset" }, "\xE2\x8A\x8A", 0x228A, SymbolClass::NegatedRelation },
    { { "supsetneq" }, "\xE2\x8A\x8B", 0x228B, SymbolClass::NegatedRelation },
    { { "nmid", "not_divides" }, "\xE2\x88\xA4", 0x2224, SymbolClass::NegatedRelation },
    { { "nparallel" }, "\xE2\x88\xA6", 0x2226, SymbolClass::NegatedRelation },
    { { "nvdash" }, "\xE2\x8A\xAC", 0x22AC, SymbolClass::NegatedRelation },
    { { "nvDash" }, "\xE2\x8A\xAD", 0x22AD, SymbolClass::NegatedRelation },
    { { "nVdash" }, "\xE2\x8A\xAE", 0x22AE, SymbolClass::NegatedRelation },
    { { "nVDash" }, "\xE2\x8A\xAF", 0x22AF, SymbolClass::NegatedRelation },
    { { "ntriangleleft" }, "\xE2\x8B\xAA", 0x22EA, SymbolClass::NegatedRelation },
    { { "ntriangleright" }, "\xE2\x8B\xAB", 0x22EB, SymbolClass::NegatedRelation },
    { { "ntrianglelefteq" }, "\xE2\x8B\xAC", 0x22EC, SymbolClass::NegatedRelation },
    { { "ntrianglerighteq" }, "\xE2\x8B\xAD", 0x22ED, SymbolClass::NegatedRelation },
};

} // namespace mathtext
} // namespace fizmo

#endif // FIZMO_MATHTEXT_SYMBOLS_RELATIONS_HPP
